import type { RecommendedAgent } from "../core/types.js";

export const recommendedAgents: Record<
  "scout" | "analyst" | "coder" | "maintainer" | "orchestrator",
  RecommendedAgent
> = {
  scout: {
    id: "wisteria-scout",
    name: "Wisteria Scout",
    description: "Discovery-only agent for repository and issue scouting.",
    profile: "minimal",
    alsoAllow: [
      "read",
      "wisteria_search_repos",
      "wisteria_search_issues",
      "wisteria_score_repo",
      "wisteria_score_issue",
      "wisteria_daily_issue_digest",
    ],
    deny: [
      "exec",
      "write",
      "apply_patch",
      "wisteria_prepare_contribution",
      "wisteria_check_workspace",
      "wisteria_create_draft_pr",
    ],
    readOnly: true,
    canWriteFiles: false,
    canExecuteCommands: false,
    canCreateDraftPr: false,
  },
  analyst: {
    id: "wisteria-analyst",
    name: "Wisteria Analyst",
    description: "Issue-analysis agent with read-only repository context access.",
    profile: "minimal",
    alsoAllow: ["read", "wisteria_get_issue_context"],
    deny: [
      "exec",
      "write",
      "apply_patch",
      "wisteria_prepare_contribution",
      "wisteria_check_workspace",
      "wisteria_create_draft_pr",
      "wisteria_daily_issue_digest",
    ],
    readOnly: true,
    canWriteFiles: false,
    canExecuteCommands: false,
    canCreateDraftPr: false,
  },
  coder: {
    id: "wisteria-coder",
    name: "Wisteria Coder",
    description: "Workspace-preparation and code-change agent without push or PR rights.",
    profile: "minimal",
    alsoAllow: [
      "read",
      "write",
      "edit",
      "apply_patch",
      "exec",
      "process",
      "wisteria_prepare_contribution",
      "wisteria_check_workspace",
    ],
    deny: ["wisteria_create_draft_pr"],
    readOnly: false,
    canWriteFiles: true,
    canExecuteCommands: true,
    canCreateDraftPr: false,
  },
  maintainer: {
    id: "wisteria-maintainer",
    name: "Wisteria Maintainer",
    description: "Verification and Draft PR agent without code editing privileges.",
    profile: "minimal",
    alsoAllow: [
      "read",
      "exec",
      "process",
      "wisteria_check_workspace",
      "wisteria_create_draft_pr",
    ],
    deny: ["write", "apply_patch", "wisteria_prepare_contribution"],
    readOnly: false,
    canWriteFiles: false,
    canExecuteCommands: true,
    canCreateDraftPr: true,
  },
  orchestrator: {
    id: "wisteria-orchestrator",
    name: "Wisteria Orchestrator",
    description: "Coordinator that asks for confirmation before risky actions.",
    profile: "minimal",
    alsoAllow: [
      "read",
      "sessions_spawn",
      "subagents",
      "sessions_list",
      "sessions_history",
      "wisteria_search_repos",
      "wisteria_search_issues",
      "wisteria_get_issue_context",
      "wisteria_daily_issue_digest",
    ],
    deny: [],
    readOnly: true,
    canWriteFiles: false,
    canExecuteCommands: false,
    canCreateDraftPr: false,
  },
};
